### ISSUE TITLE
compile code

### ISSUE THREAD

**Issue by ediaz** [javachessgui/javachessgui2#1]
Hi, 
Thanks for your code. I came across your thread on chess.com . I was trying to run your jar file, but got 
"Unsupported major.minor version 52.0".

I tried to compiled myself but no success. Could you contribute the build.xml file you use for compiling and building the jar file?

Esteban

**Comment by ediaz** [comment]
I think you can add the project nbproject/build-impl.xml builder

**Comment by javachessgui** [comment]
Unfortunately I have long abandoned this project for a chess GUI written in Scala ( I no longer have the project on my disk ). Scalachessgui is also based on JavaFX ( as Scala runs on the JVM and can use Java packages ) and is packaged in a jar as well. It has all the build files so you can build it using sbt ( Simple Build Tool ). See: https://github.com/scalachessgui/scalachessgui. In any case I recommend that you use the latest available Java runtime environment to run the jar executables.

**Comment by ediaz** [comment]
Thanks for the quick reply, I'll look into your scala project. Did you know lichess runs on scala? Maybe you can take a look at it. 
Cheers.

**Comment by javachessgui** [comment]
The reason I switched to Scala was because as a lichess member I came to appreciate the efficiency of this language ( I first learned about Scala at lichess and I wondered about the language that makes such a great site possible ). Also NetBeans is too complicated and slow. It is much easier to use the incremental compiler provided by sbt. Scalachessgui is specifically desgined to support lichess variants ( currently only crazyhouse is not supported ). I received feedback from both chess.com and lichess that scalachessgui was successully run by others. I'm also aware that there can be platforms where chess fonts don't render correctly, for example this happened on Mac OS X. I have also developed bitboard engines for lichess variants Atomic, Racing Kings and Horde : https://github.com/chessvariantengine.
